# Prometheus 설정 파일
# Exoplanet Detection API 모니터링

global:
  scrape_interval: 15s  # 15초마다 메트릭 수집
  evaluation_interval: 15s  # 15초마다 규칙 평가
  external_labels:
    monitor: 'exoplanet-detection-monitor'
    environment: 'production'

# Alertmanager 설정 (선택사항)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: []

# 규칙 파일 로드
rule_files:
  # - "alerts.yml"

# 스크랩 설정
scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'

  # FastAPI 백엔드 모니터링
  - job_name: 'exoplanet-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s  # API는 더 자주 수집
    scrape_timeout: 3s

  # Node Exporter (시스템 메트릭)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
